/// Whether Steam's menu has the controller, as gamescope reports it.
///
/// **Under gamescope the window never loses focus.** Steam Game Mode runs two
/// Xwayland servers: Steam and its menu on `:0`, games — Glassfin included — on
/// `:1`. When the menu opens, gamescope moves its own input focus to the menu's
/// window, but it only calls `XSetInputFocus` among each server's own windows,
/// so nothing on `:1` receives a FocusOut and GTK has nothing to report. Read in
/// gamescope's `steamcompmgr.cpp` at 3.16.19, and confirmed on the BC-250: 0.2.3
/// gated the pad on window focus and logged no focus change at all.
///
/// What does change is on `:0`'s root window. On every focus change gamescope
/// writes `GAMESCOPE_FOCUSED_APP`, the Steam app id of whatever has input, and
/// `GAMESCOPE_FOCUSED_APP_GFX`, the app whose picture is on screen. On the
/// BC-250 the first flipped between Glassfin's shortcut id and Steam's (769) at
/// every open and close of the menu, and read 769 through the presses that
/// started an episode; the second stayed Glassfin's throughout.
///
/// **Reaching `:0` from the sandbox.** The Flatpak only gets `:1`'s socket file,
/// but it shares the host network namespace, and Xwayland also listens on an
/// abstract socket that lives in that namespace. Steam's display needs no
/// authorisation cookie. If any of that stops being true, the watcher reports
/// itself unavailable and the pad keeps working exactly as before.
library;

import 'dart:async';
import 'dart:ffi';
import 'dart:isolate';

import 'package:ffi/ffi.dart';
import 'package:flutter/foundation.dart';

/// gamescope's root Xwayland server, where Steam runs and the properties live.
const String steamDisplay = ':0';

/// Steam's own app id, which is what gamescope reports while its menu has input.
const int steamAppId = 769;

/// How often the watcher drains X events. The same as the SDL poll: a focus
/// change is only useful up to the rate at which the pad is read.
const Duration _pollInterval = Duration(milliseconds: 50);

/// Decides from gamescope's two properties whether Glassfin has input.
///
/// Pure, so it can be tested without an X server.
class GamescopeFocusReading {
  int? _ownApp;

  /// Glassfin's app id as gamescope knows it, once it has been seen.
  int? get ownApp => _ownApp;

  /// True when Glassfin has input, false when something else does, and null
  /// when the properties cannot say.
  ///
  /// **Glassfin's id is learned from the picture, never assumed.** A non-Steam
  /// shortcut's id is generated by Steam and differs per machine, so it is taken
  /// from the first `GAMESCOPE_FOCUSED_APP_GFX` that is set and is not Steam's.
  /// Until then there is no opinion — and none means the pad stays live, which
  /// is the only safe default: learning 769 as "ours" at launch, before
  /// Glassfin's window is up, would mute the pad everywhere except Steam's menu.
  bool? update({required int focusedApp, required int baseApp}) {
    if (_ownApp == null && baseApp != 0 && baseApp != steamAppId) {
      _ownApp = baseApp;
    }
    final own = _ownApp;
    if (own == null || focusedApp == 0) return null;
    return focusedApp == own;
  }
}

/// Watches gamescope's focus properties on [steamDisplay].
///
/// **In an isolate of its own**, because `XOpenDisplay` blocks for as long as a
/// server takes to answer, and a listening socket with nothing serving it never
/// does — the workstation has exactly such a `:1`. Blocking there on the UI
/// isolate would freeze the interface for good; blocking in a spare isolate
/// costs a thread.
class GamescopeFocus {
  GamescopeFocus({required this.onChange, this.onProperties});

  /// Whether Glassfin has input, with a short description for the log.
  final void Function(bool focused, String detail) onChange;

  /// Every change to the raw properties, for input logging.
  final void Function(int focusedApp, int baseApp)? onProperties;

  final GamescopeFocusReading _reading = GamescopeFocusReading();
  Isolate? _isolate;
  ReceivePort? _port;
  bool? _last;

  Future<void> start() async {
    if (_isolate != null) return;
    final port = ReceivePort();
    _port = port;
    port.listen(_onMessage);
    try {
      _isolate = await Isolate.spawn(
        _watch,
        port.sendPort,
        debugName: 'gamescope-focus',
      );
    } on Object catch (error) {
      debugPrint('input: gamescope focus watcher did not start — $error');
      stop();
    }
  }

  void stop() {
    _isolate?.kill(priority: Isolate.immediate);
    _isolate = null;
    _port?.close();
    _port = null;
  }

  void _onMessage(Object? message) {
    switch (message) {
      case ('opened', final String display):
        debugPrint('input: watching gamescope focus on $display');
      case ('unavailable', final String reason):
        // Normal on any desktop. One line, so a pad that still leaks behind
        // Steam's menu can be traced to the watcher never having started.
        debugPrint(
          'input: gamescope focus unavailable ($reason); window focus only',
        );
        stop();
      case ('properties', final int focusedApp, final int baseApp):
        onProperties?.call(focusedApp, baseApp);
        final hadOwn = _reading.ownApp != null;
        final focused = _reading.update(
          focusedApp: focusedApp,
          baseApp: baseApp,
        );
        if (!hadOwn && _reading.ownApp != null) {
          debugPrint(
            'input: gamescope knows Glassfin as app ${_reading.ownApp}',
          );
        }
        if (focused == null) {
          // **Not a report either way.** Counting it as "focused" would let the
          // gate treat gamescope as having seen focus, and the brief moment at
          // launch when Glassfin is on screen but Steam still has input would
          // then mute the pad. It only undoes a mute gamescope itself caused.
          if (_last != false) return;
          _last = null;
          onChange(true, 'gamescope cannot tell who has input');
          return;
        }
        if (focused == _last) return;
        _last = focused;
        onChange(focused, 'gamescope app $focusedApp has input');
    }
  }
}

// Xlib constants, from X.h.
const int _propertyChangeMask = 1 << 22;
const int _propertyNotify = 28;
const int _success = 0;

/// `XEvent` is a 24-long union: 192 bytes on 64-bit. Over-allocated.
const int _eventBytes = 256;

/// Where `atom` sits in an `XPropertyEvent` on LP64: `int type`, then
/// `unsigned long serial`, `Bool send_event`, `Display *display`,
/// `Window window`, each padded to 8 bytes.
const int _propertyEventAtomOffset = 40;

/// The handful of Xlib functions the watcher needs.
class _X11 {
  _X11(DynamicLibrary library)
    : openDisplay = library
          .lookupFunction<
            Pointer<Void> Function(Pointer<Utf8>),
            Pointer<Void> Function(Pointer<Utf8>)
          >('XOpenDisplay'),
      closeDisplay = library
          .lookupFunction<
            Int32 Function(Pointer<Void>),
            int Function(Pointer<Void>)
          >('XCloseDisplay'),
      defaultRootWindow = library
          .lookupFunction<
            UnsignedLong Function(Pointer<Void>),
            int Function(Pointer<Void>)
          >('XDefaultRootWindow'),
      internAtom = library
          .lookupFunction<
            UnsignedLong Function(Pointer<Void>, Pointer<Utf8>, Int32),
            int Function(Pointer<Void>, Pointer<Utf8>, int)
          >('XInternAtom'),
      selectInput = library
          .lookupFunction<
            Int32 Function(Pointer<Void>, UnsignedLong, Long),
            int Function(Pointer<Void>, int, int)
          >('XSelectInput'),
      pending = library
          .lookupFunction<
            Int32 Function(Pointer<Void>),
            int Function(Pointer<Void>)
          >('XPending'),
      nextEvent = library
          .lookupFunction<
            Int32 Function(Pointer<Void>, Pointer<Void>),
            int Function(Pointer<Void>, Pointer<Void>)
          >('XNextEvent'),
      getWindowProperty = library
          .lookupFunction<
            Int32 Function(
              Pointer<Void>,
              UnsignedLong,
              UnsignedLong,
              Long,
              Long,
              Int32,
              UnsignedLong,
              Pointer<UnsignedLong>,
              Pointer<Int32>,
              Pointer<UnsignedLong>,
              Pointer<UnsignedLong>,
              Pointer<Pointer<Uint8>>,
            ),
            int Function(
              Pointer<Void>,
              int,
              int,
              int,
              int,
              int,
              int,
              Pointer<UnsignedLong>,
              Pointer<Int32>,
              Pointer<UnsignedLong>,
              Pointer<UnsignedLong>,
              Pointer<Pointer<Uint8>>,
            )
          >('XGetWindowProperty'),
      free = library
          .lookupFunction<
            Int32 Function(Pointer<Void>),
            int Function(Pointer<Void>)
          >('XFree');

  final Pointer<Void> Function(Pointer<Utf8>) openDisplay;
  final int Function(Pointer<Void>) closeDisplay;
  final int Function(Pointer<Void>) defaultRootWindow;
  final int Function(Pointer<Void>, Pointer<Utf8>, int) internAtom;
  final int Function(Pointer<Void>, int, int) selectInput;
  final int Function(Pointer<Void>) pending;
  final int Function(Pointer<Void>, Pointer<Void>) nextEvent;
  final int Function(
    Pointer<Void>,
    int,
    int,
    int,
    int,
    int,
    int,
    Pointer<UnsignedLong>,
    Pointer<Int32>,
    Pointer<UnsignedLong>,
    Pointer<UnsignedLong>,
    Pointer<Pointer<Uint8>>,
  )
  getWindowProperty;
  final int Function(Pointer<Void>) free;

  static _X11? open() {
    for (final name in const ['libX11.so.6', 'libX11.so']) {
      try {
        return _X11(DynamicLibrary.open(name));
      } on ArgumentError {
        continue;
      }
    }
    return null;
  }

  /// An existing atom, or 0. **Never creates one:** an atom gamescope has not
  /// made is the sign this display is not gamescope's.
  int existingAtom(Pointer<Void> display, String name) {
    final native = name.toNativeUtf8();
    try {
      return internAtom(display, native, 1);
    } finally {
      calloc.free(native);
    }
  }

  /// The first value of a 32-bit property, or 0 when it is unset or empty —
  /// gamescope writes `GAMESCOPE_FOCUSED_APP` with no items when nothing has
  /// input.
  int cardinal(Pointer<Void> display, int window, int atom) {
    final type = calloc<UnsignedLong>();
    final format = calloc<Int32>();
    final items = calloc<UnsignedLong>();
    final after = calloc<UnsignedLong>();
    final data = calloc<Pointer<Uint8>>();
    try {
      final status = getWindowProperty(
        display,
        window,
        atom,
        0,
        1,
        0,
        0,
        type,
        format,
        items,
        after,
        data,
      );
      if (status != _success || data.value == nullptr) return 0;
      // Xlib returns 32-bit items as C longs, sign-extended: a shortcut id of
      // 3158376258 comes back negative without the mask.
      final value = format.value == 32 && items.value > 0
          ? data.value.cast<UnsignedLong>().value & 0xFFFFFFFF
          : 0;
      free(data.value.cast());
      return value;
    } finally {
      calloc.free(type);
      calloc.free(format);
      calloc.free(items);
      calloc.free(after);
      calloc.free(data);
    }
  }
}

/// The watcher isolate's entry point.
///
/// **A timer, not a blocking `XNextEvent` loop,** so the isolate returns to its
/// event loop between drains and `Isolate.kill` can end it. A thread parked in
/// native code would outlive the kill and could hold up the VM's shutdown.
void _watch(SendPort out) {
  final x = _X11.open();
  if (x == null) {
    out.send(('unavailable', 'no libX11'));
    return;
  }

  final name = steamDisplay.toNativeUtf8();
  final display = x.openDisplay(name);
  calloc.free(name);
  if (display == nullptr) {
    out.send(('unavailable', 'cannot open $steamDisplay'));
    return;
  }

  final focusedAtom = x.existingAtom(display, 'GAMESCOPE_FOCUSED_APP');
  final baseAtom = x.existingAtom(display, 'GAMESCOPE_FOCUSED_APP_GFX');
  if (focusedAtom == 0 || baseAtom == 0) {
    x.closeDisplay(display);
    out.send(('unavailable', '$steamDisplay is not gamescope'));
    return;
  }

  final root = x.defaultRootWindow(display);
  x.selectInput(display, root, _propertyChangeMask);
  out.send(('opened', steamDisplay));

  var last = (-1, -1);
  void report() {
    final now = (
      x.cardinal(display, root, focusedAtom),
      x.cardinal(display, root, baseAtom),
    );
    if (now == last) return;
    last = now;
    out.send(('properties', now.$1, now.$2));
  }

  report();

  final event = calloc<Uint8>(_eventBytes);
  Timer.periodic(_pollInterval, (_) {
    var relevant = false;
    while (x.pending(display) > 0) {
      x.nextEvent(display, event.cast());
      if (event.cast<Int32>().value != _propertyNotify) continue;
      final atom = (event + _propertyEventAtomOffset)
          .cast<UnsignedLong>()
          .value;
      if (atom == focusedAtom || atom == baseAtom) relevant = true;
    }
    if (relevant) report();
  });
}
